## Load packages

In [1]:
# load packages
import numpy as np
import pandas as pd
import os
import pathlib
import json
working_dir = pathlib.Path().absolute()
os.chdir(working_dir)

In [2]:
working_dir

WindowsPath('c:/Users/mmiesen/OneDrive - Bionano Genomics/Desktop/Bionano/my_curation')

## Loading Data

In [3]:
# load data
hg002_path = "postnatal_curation_review_complete.csv"
df = pd.read_csv(hg002_path, index_col=False)

In [1]:
df.shape

NameError: name 'df' is not defined

In [5]:
df.dtypes

svcurationdatapk     int64
classification      object
smapentryid          int64
svtype              object
notes               object
refid1               int64
refid2               int64
svjson              object
userfk               int64
curation_role       object
fullname            object
tabletype            int64
jobid                int64
samplename          object
samplefk             int64
objectalias         object
dtype: object

In [6]:
# pd.io.json.json_normalize(df.acList.apply(json.loads))
json_df = pd.json_normalize(df['svjson'].apply(json.loads))

In [7]:
json_df.dtypes

Type                                    object
Mask                                   float64
SuperType                              float64
SmapEntryID                            float64
QryContigID                            float64
RefcontigID1                           float64
RefcontigID2                           float64
QryStartPos                            float64
QryEndPos                              float64
RefStartPos                            float64
RefEndPos                              float64
Confidence                             float64
Orientation                             object
VAF                                    float64
ISCN                                    object
QryStartIdx                            float64
QryEndIdx                              float64
RefStartIdx                            float64
RefEndIdx                              float64
Zygosity                                object
Genotype                               float64
GenotypeGroup                          float64
RawConfidence                          float64
Size                                   float64
InLOH                                  float64
PosteriorProb                          float64
Algorithm                               object
Sample                                  object
presentInPctOfBngControlSamples        float64
presentInPctOfBngControlSameSamples    float64
failAssemblyChimericScore               object
overlapGenes                            object
nearestNonOverlapGene                   object
nearestNonOverlapGeneDistance           object
putativeGeneFusion                      object
moleculeCount                          float64
numOverlapDgvCalls                     float64
ucscWebLink1                            object
ucscWebLink2                            object
foundInSelfMolecules                    object
id                                     float64
start                                  float64
end                                    float64
type                                    object
fractionalCopyNumber                   float64
copyNumber                             float64
confidence                             float64
size                                   float64
vaf                                     object
algorithm                               object
BrkptEdges_Start_Ref_1_Pos             float64
BrkptEdges_Start_Ref_2_Pos             float64
BrkptEdges_End_Qry_1                   float64
BrkptEdges_End_Qry_2                   float64
foundInControlSampleAssembly            object
foundInControlSampleMolecules           object
controlMoleculeCount                   float64
dtype: object

In [8]:
display(df)
display(json_df)

,svcurationdatapk,classification,smapentryid,svtype,notes,refid1,refid2,svjson,userfk,curation_role,fullname,tabletype,jobid,samplename,samplefk,objectalias
0,44029,Likely benign,286,InDels,NaN,1,1,"{""Type"":""deletion"",""Mask"":0,""SuperType"":2,""Sma...",24,Analyst,Mike Gallagher,1,2628,BNGOKH-0001585,1156,BNGOKH-0001585 - De novo
1,44029,Likely benign,286,InDels,NaN,1,1,"{""Type"":""deletion"",""Mask"":0,""SuperType"":2,""Sma...",24,Analyst,Mike Gallagher,2,2628,BNGOKH-0001585,1156,BNGOKH-0001585 - De novo
2,44030,Likely benign,1491,InDels,NaN,2,2,"{""Type"":""insertion"",""Mask"":0,""SuperType"":1,""Sm...",24,Analyst,Mike Gallagher,1,2628,BNGOKH-0001585,1156,BNGOKH-0001585 - De novo
3,44030,Likely benign,1491,InDels,NaN,2,2,"{""Type"":""insertion"",""Mask"":0,""SuperType"":1,""Sm...",24,Analyst,Mike Gallagher,2,2628,BNGOKH-0001585,1156,BNGOKH-0001585 - De novo
4,44032,Likely benign,3009,InDels,NaN,3,3,"{""Type"":""deletion"",""Mask"":0,""SuperType"":2,""Sma...",24,Analyst,Mike Gallagher,1,2628,BNGOKH-0001585,1156,BNGOKH-0001585 - De novo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66509,55909,Likely benign,16373,InDels,NaN,22,22,"{""Type"":""insertion"",""Mask"":0,""SuperType"":1,""Sm...",54,Supervisor,Roger Stevenson,1,3128,BNGOKH-0000950,714,BNGOKH-0000950 - De novo
66510,55909,Uncertain significance,16373,InDels,RNR,22,22,"{""Type"":""insertion"",""Mask"":0,""SuperType"":1,""Sm...",8,Analyst,Ben Clifford,2,3128,BNGOKH-0000950,714,BNGOKH-0000950 - De novo
66511,55910,Benign,17322,InDels,NaN,24,24,"{""Type"":""insertion"",""Mask"":0,""SuperType"":1,""Sm...",8,Analyst,Ben Clifford,1,3128,BNGOKH-0000950,714,BNGOKH-0000950 - De novo
66512,55910,Benign,17322,InDels,NaN,24,24,"{""Type"":""insertion"",""Mask"":0,""SuperType"":1,""Sm...",8,Analyst,Ben Clifford,2,3128,BNGOKH-0000950,714,BNGOKH-0000950 - De novo
66513,55910,Benign,17322,InDels,NaN,24,24,"{""Type"":""insertion"",""Mask"":0,""SuperType"":1,""Sm...",8,Analyst,Ben Clifford,2,3128,BNGOKH-0000950,714,BNGOKH-0000950 - De novo

,Type,Mask,SuperType,SmapEntryID,QryContigID,RefcontigID1,RefcontigID2,QryStartPos,QryEndPos,RefStartPos,...,size,vaf,algorithm,BrkptEdges_Start_Ref_1_Pos,BrkptEdges_Start_Ref_2_Pos,BrkptEdges_End_Qry_1,BrkptEdges_End_Qry_2,foundInControlSampleAssembly,foundInControlSampleMolecules,controlMoleculeCount
0,deletion,0.0,2.0,286.0,11.0,1.0,1.0,90494551.1,90505701.0,30002013.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,deletion,0.0,2.0,286.0,11.0,1.0,1.0,90494551.1,90505701.0,30002013.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,insertion,0.0,1.0,1491.0,102.0,2.0,2.0,86184147.5,86232412.8,1512267.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,insertion,0.0,1.0,1491.0,102.0,2.0,2.0,86184147.5,86232412.8,1512267.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,deletion,0.0,2.0,3009.0,92.0,3.0,3.0,5883127.6,5887461.9,84799609.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66509,insertion,0.0,1.0,16373.0,381.0,22.0,22.0,24155444.1,24202745.5,45184845.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66510,insertion,0.0,1.0,16373.0,381.0,22.0,22.0,24155444.1,24202745.5,45184845.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66511,insertion,0.0,1.0,17322.0,680.0,24.0,24.0,811277.7,854454.2,21850935.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66512,insertion,0.0,1.0,17322.0,680.0,24.0,24.0,811277.7,854454.2,21850935.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66513,insertion,0.0,1.0,17322.0,680.0,24.0,24.0,811277.7,854454.2,21850935.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

assume the order is correct. then, we concatenate columns in json_df to the right of df

In [9]:
out_df = pd.concat([df, json_df], axis=1)

In [10]:
out_df.shape

(66514, 73)

save for future use (output)

In [11]:
out_df.to_csv(rf"output\concat_curation_json.csv", index=False)

Re-import main table

In [12]:
df = pd.read_csv("output\concat_curation_json.csv", index_col=False)
df = df.astype({'Size':'str','Type':'str'})
df.head()

C:\Users\mmiesen\AppData\Local\Temp\ipykernel_14000\2393633948.py:1: DtypeWarning: Columns (70,71) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("output\concat_curation_json.csv", index_col=False)

,svcurationdatapk,classification,smapentryid,svtype,notes,refid1,refid2,svjson,userfk,curation_role,...,size,vaf,algorithm,BrkptEdges_Start_Ref_1_Pos,BrkptEdges_Start_Ref_2_Pos,BrkptEdges_End_Qry_1,BrkptEdges_End_Qry_2,foundInControlSampleAssembly,foundInControlSampleMolecules,controlMoleculeCount
0,44029,Likely benign,286,InDels,NaN,1,1,"{""Type"":""deletion"",""Mask"":0,""SuperType"":2,""Sma...",24,Analyst,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,44029,Likely benign,286,InDels,NaN,1,1,"{""Type"":""deletion"",""Mask"":0,""SuperType"":2,""Sma...",24,Analyst,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,44030,Likely benign,1491,InDels,NaN,2,2,"{""Type"":""insertion"",""Mask"":0,""SuperType"":1,""Sm...",24,Analyst,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,44030,Likely benign,1491,InDels,NaN,2,2,"{""Type"":""insertion"",""Mask"":0,""SuperType"":1,""Sm...",24,Analyst,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,44032,Likely benign,3009,InDels,NaN,3,3,"{""Type"":""deletion"",""Mask"":0,""SuperType"":2,""Sma...",24,Analyst,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.columns

Index(['svcurationdatapk', 'classification', 'smapentryid', 'svtype', 'notes',
       'refid1', 'refid2', 'svjson', 'userfk', 'curation_role', 'fullname',
       'tabletype', 'jobid', 'samplename', 'samplefk', 'objectalias', 'Type',
       'Mask', 'SuperType', 'SmapEntryID', 'QryContigID', 'RefcontigID1',
       'RefcontigID2', 'QryStartPos', 'QryEndPos', 'RefStartPos', 'RefEndPos',
       'Confidence', 'Orientation', 'VAF', 'ISCN', 'QryStartIdx', 'QryEndIdx',
       'RefStartIdx', 'RefEndIdx', 'Zygosity', 'Genotype', 'GenotypeGroup',
       'RawConfidence', 'Size', 'InLOH', 'PosteriorProb', 'Algorithm',
       'Sample', 'presentInPctOfBngControlSamples',
       'presentInPctOfBngControlSameSamples', 'failAssemblyChimericScore',
       'overlapGenes', 'nearestNonOverlapGene',
       'nearestNonOverlapGeneDistance', 'putativeGeneFusion', 'moleculeCount',
       'numOverlapDgvCalls', 'ucscWebLink1', 'ucscWebLink2',
       'foundInSelfMolecules', 'id', 'start', 'end', 'type',
       'fractionalCopyNumber', 'copyNumber', 'confidence', 'size', 'vaf',
       'algorithm', 'BrkptEdges_Start_Ref_1_Pos', 'BrkptEdges_Start_Ref_2_Pos',
       'BrkptEdges_End_Qry_1', 'BrkptEdges_End_Qry_2',
       'foundInControlSampleAssembly', 'foundInControlSampleMolecules',
       'controlMoleculeCount'],
      dtype='object')

In [14]:
#color by SV (R,G,B)
def get_sv_type(type_str):
    type_str = type_str.strip()
    if "del" in type_str:
        return "255,0,0"
    elif "dup" in type_str:
         # ignore duplications to stay in concordance with ctrl_df['Type]
        return "0,0,255" #blue
    elif "ins" in type_str:
        return "0,0,255"
    elif "inv" in type_str:
        return "0,255,255"
    elif "trans" in type_str:
        return "255,0,255"
    elif "mono" in type_str:
        return "255,0,0"
    elif "tri" in type_str:
        return "0,0,255"
    elif "rear" in type_str:
        return "128,0,128"
    else:
        return(type_str)

#outputting SV colors using python for loops
for type in df.loc[:3,'Type']:
    print(get_sv_type(type))

#adding SV colors column using pandas
#.apply calls pandas to use lambda function
df['Color'] = df.apply(lambda x: get_sv_type(x['Type']), axis=1)

#shows first 5 rows of dataframe
df.head()

255,0,0
255,0,0
0,0,255
0,0,255

,svcurationdatapk,classification,smapentryid,svtype,notes,refid1,refid2,svjson,userfk,curation_role,...,vaf,algorithm,BrkptEdges_Start_Ref_1_Pos,BrkptEdges_Start_Ref_2_Pos,BrkptEdges_End_Qry_1,BrkptEdges_End_Qry_2,foundInControlSampleAssembly,foundInControlSampleMolecules,controlMoleculeCount,Color
0,44029,Likely benign,286,InDels,NaN,1,1,"{""Type"":""deletion"",""Mask"":0,""SuperType"":2,""Sma...",24,Analyst,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"255,0,0"
1,44029,Likely benign,286,InDels,NaN,1,1,"{""Type"":""deletion"",""Mask"":0,""SuperType"":2,""Sma...",24,Analyst,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"255,0,0"
2,44030,Likely benign,1491,InDels,NaN,2,2,"{""Type"":""insertion"",""Mask"":0,""SuperType"":1,""Sm...",24,Analyst,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0,0,255"
3,44030,Likely benign,1491,InDels,NaN,2,2,"{""Type"":""insertion"",""Mask"":0,""SuperType"":1,""Sm...",24,Analyst,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0,0,255"
4,44032,Likely benign,3009,InDels,NaN,3,3,"{""Type"":""deletion"",""Mask"":0,""SuperType"":2,""Sma...",24,Analyst,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"255,0,0"

In [15]:
# popuilate name column
# df["Period"] = df[["Courses", "Duration"]].apply("-".join, axis=1)

# Name
# 	- Size_Type_ISCN_Classification
# 	- Zygosity?
# Prevalence (n patients)


# df['name'] = df[["Size", "Type", "ISCN", "classification"]].apply("_".join, axis=1)
df['name'] = df['Size'].astype(str) + "_" + df["Type"] + "_" + df["ISCN"] + "_" + df["classification"]

In [16]:
# BED mandatory columns (chr, refstart, refpos, name, color)
# chr1	1	121700000	MM_1p_Wholearm_Deletion_US					255,0,0
bed_df = df[['refid1', 'RefStartPos', 'RefEndPos', 'name', 'Color']]
bed_df["refid1"] = "chr" + bed_df["refid1"].astype(str)
bed_df.head()

C:\Users\mmiesen\AppData\Local\Temp\ipykernel_14000\2094250939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bed_df["refid1"] = "chr" + bed_df["refid1"].astype(str)

,refid1,RefStartPos,RefEndPos,name,Color
0,chr1,30002013.0,30022777.0,9614.1_deletion_ogm[GRCh38] 1p35.2(30002013_30...,"255,0,0"
1,chr1,30002013.0,30022777.0,9614.1_deletion_ogm[GRCh38] 1p35.2(30002013_30...,"255,0,0"
2,chr2,1512267.0,1538271.0,22261.3_insertion_ogm[GRCh38] ins(2;?)(p25.3;?...,"0,0,255"
3,chr2,1512267.0,1538271.0,22261.3_insertion_ogm[GRCh38] ins(2;?)(p25.3;?...,"0,0,255"
4,chr3,84799609.0,84830635.0,26691.7_deletion_ogm[GRCh38] 3p12.1(84799609_8...,"255,0,0"

In [17]:
df[["Size", "Type", "ISCN", "classification"]].dtypes

Size              object
Type              object
ISCN              object
classification    object
dtype: object

In [18]:
bed_df.head()

,refid1,RefStartPos,RefEndPos,name,Color
0,chr1,30002013.0,30022777.0,9614.1_deletion_ogm[GRCh38] 1p35.2(30002013_30...,"255,0,0"
1,chr1,30002013.0,30022777.0,9614.1_deletion_ogm[GRCh38] 1p35.2(30002013_30...,"255,0,0"
2,chr2,1512267.0,1538271.0,22261.3_insertion_ogm[GRCh38] ins(2;?)(p25.3;?...,"0,0,255"
3,chr2,1512267.0,1538271.0,22261.3_insertion_ogm[GRCh38] ins(2;?)(p25.3;?...,"0,0,255"
4,chr3,84799609.0,84830635.0,26691.7_deletion_ogm[GRCh38] 3p12.1(84799609_8...,"255,0,0"

In [19]:
bed_df.dtypes

refid1          object
RefStartPos    float64
RefEndPos      float64
name            object
Color           object
dtype: object

In [20]:
bed_df = bed_df.fillna(0)
bed_df = bed_df.astype({'RefStartPos':'int64'})
bed_df = bed_df.astype({'RefEndPos':'int64'})

In [21]:
bed_df

,refid1,RefStartPos,RefEndPos,name,Color
0,chr1,30002013,30022777,9614.1_deletion_ogm[GRCh38] 1p35.2(30002013_30...,"255,0,0"
1,chr1,30002013,30022777,9614.1_deletion_ogm[GRCh38] 1p35.2(30002013_30...,"255,0,0"
2,chr2,1512267,1538271,22261.3_insertion_ogm[GRCh38] ins(2;?)(p25.3;?...,"0,0,255"
3,chr2,1512267,1538271,22261.3_insertion_ogm[GRCh38] ins(2;?)(p25.3;?...,"0,0,255"
4,chr3,84799609,84830635,26691.7_deletion_ogm[GRCh38] 3p12.1(84799609_8...,"255,0,0"
...,...,...,...,...,...
66509,chr22,45184845,45199562,32584.4_insertion_ogm[GRCh38] ins(22;?)(q13.31...,"0,0,255"
66510,chr22,45184845,45199562,32584.4_insertion_ogm[GRCh38] ins(22;?)(q13.31...,"0,0,255"
66511,chr24,21850935,21870133,23978.5_insertion_ogm[GRCh38] ins(24;?)(q11.22...,"0,0,255"
66512,chr24,21850935,21870133,23978.5_insertion_ogm[GRCh38] ins(24;?)(q11.22...,"0,0,255"
66513,chr24,21850935,21870133,23978.5_insertion_ogm[GRCh38] ins(24;?)(q11.22...,"0,0,255"

In [22]:
df["Type"]

0         deletion
1         deletion
2        insertion
3        insertion
4         deletion
           ...
66509    insertion
66510    insertion
66511    insertion
66512    insertion
66513    insertion
Name: Type, Length: 66514, dtype: object

In [23]:
get_sv_type("deletion")

'255,0,0'

In [24]:
bed_df.to_csv("output\ curationpt1.bed", index=False, sep='\t', header=None)